language: node_js
node_js:
  - "11"
jdk:
  - oraclejdk8  
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=imaxmunguia-github -Dsonar.projectKey=DAV.ConsultaVirtual -Dsonar.sources='./app' -X